### ISSUE TITLE
Is this repository licensed under the Apache 2.0 license?

### ISSUE THREAD

**Issue by awssenera** [h2oai/h2o3-sagemaker#10]
Hi,

Is this repository licensed under the Apache 2.0 license? Would it be possible to add this license to this repository. I would like to use an upgraded version of it as a piece of an upcoming AWS blog. I would be really glad to have it soon.

Thank you very much,
Anil Sener

**Comment by ledell** [comment]
Hi @awssenera we added an Apache 2.0 license: https://github.com/h2oai/h2o3-sagemaker/commit/d8946e447d16bb67a78d8bf24de93650f755f4fe
